spring:
  profiles:
    active: helloWorld
  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      auto-offset-reset: latest          # should new consumer read from the latest (default) or from the beginning ?
